
compile:
	g++ -o plotpowrat_numfrac plotpowrat_numfrac.C read_data.C plot_Joy.C `root-config --cflags` `root-config --glibs`
	rm -f *.o
	mkdir plot
	@echo " "
	@echo "Compilazione completata!"
	@echo " "
