####################################
# ELECTRON BEAM                    #
# BACKSCATTER                      #
# Anton.Lechner@cern.ch            #
####################################
#
#
#############
# VERBOSITY #
#############
#
/control/verbose 1
/tracking/verbose 0
/run/verbose 0
/event/verbose 0
#
#
################
# PHYSICS LIST #
################
#
/testem/phys/addPhysics emstandard_opt4
#
###################
# PHYSICS OPTIONS #
###################
#
#/process/eLoss/StepFunction        0.2  100.0 um
#/process/msc/RangeFactor  0.01
#/process/msc/Skin  3
#
######################
# RUN INITIALIZATION #
######################
#
/run/initialize
#
/testem/phys/setCuts 1 um
/testem/stepMax      1 km
#
# ### Test A: Aluminum target
#
######################## 
# DETECTOR DESCRIPTION #
########################
#
/detector/material           G4_Al
/detector/length             0.264 cm
/detector/radius             2.54 cm
#/detector/maxStepSize        1 m
#/detector/prodCut            1.0 um         
#
# #############################################################
# ### Run No 1
# #############################################################
#
#################### 
# BEAM DESCRIPTION #
####################
#
/beam/energy                 1.033 MeV
/beam/sigma                  0.0
/beam/angle                  60.0 deg
#
#################################
# TEST AGAINST EXPECTED VALUES  #
#################################
#
/detector/energyAlbedoTestValue  0.195
/detector/chargeAlbedoTestValue  0.337
#
#############
# START RUN #
#############
#
/run/beamOn 50000
#
#
# #############################################################
# ### Run No 2
# #############################################################
#
#################### 
# BEAM DESCRIPTION #
####################
#
/beam/energy                 0.109 MeV
/beam/sigma                  0.0
/beam/angle                  60.0 deg
#
#################################
# TEST AGAINST EXPECTED VALUES  #
#################################
#
/detector/energyAlbedoTestValue  0.266
/detector/chargeAlbedoTestValue  0.365
#
#############
# START RUN #
#############
#
/run/beamOn 50000
#
#
#
#
# ### Test B: Molybdenum target
#
#
######################## 
# DETECTOR DESCRIPTION #
########################
#
/detector/material           G4_Mo
/detector/length             0.091 cm
/detector/radius             2.54 cm
#/detector/maxStepSize        1 m
#/detector/prodCut            1.0 um         
#
#
# #############################################################
# ### Run No 3
# #############################################################
#
#################### 
# BEAM DESCRIPTION #
####################
#
/beam/energy                 1.033 MeV
/beam/sigma                  0.0
/beam/angle                  60.0 deg
#
#################################
# TEST AGAINST EXPECTED VALUES  #
#################################
#
/detector/energyAlbedoTestValue  0.394
/detector/chargeAlbedoTestValue  0.530
#
#############
# START RUN #
#############
#
/run/beamOn 50000
#
#
# #############################################################
# ### Run No 4
# #############################################################
#
#################### 
# BEAM DESCRIPTION #
####################
#
/beam/energy                 0.109 MeV
/beam/sigma                  0.0
/beam/angle                  60.0 deg
#
#################################
# TEST AGAINST EXPECTED VALUES  #
#################################
#
/detector/energyAlbedoTestValue  0.464
/detector/chargeAlbedoTestValue  0.564
#
#############
# START RUN #
#############
#
/run/beamOn 50000
