####################################
# e- BEAM                          #
####################################
#
#
#############
# VERBOSITY #
#############
#
/control/verbose 1
/tracking/verbose 0
/run/verbose 0
/event/verbose 0
#
#
###########
# PHYSICS #
###########
#
/testem/phys/addPhysics PHYSLIST
/testem/phys/addPhysics standardGS
#
#
#
#
######################
# RUN INITIALIZATION #
######################
#
/run/initialize
#
#/testem/phys/setCuts CUTS
#/testem/stepMax      STEPMAX
#
#/process/eLoss/StepFunction        0.2  100.0 um
#
#/process/msc/RangeFactor  0.01
#/process/msc/Skin  3
#
#
######################## 
# DETECTOR DESCRIPTION #
########################
#
/detector/material           G4_Al
/detector/length             0.264 cm
/detector/radius             2.54 cm
#/detector/maxStepSize        1 m
#/detector/prodCut            0.9508 um         
#
#
/beam/angle                  0.0 deg
#
#
# #############################################################
# ### Run No 1
# #############################################################
#
#################### 
# BEAM DESCRIPTION #
####################
#
/beam/energy                 1.033 MeV
/beam/sigma                  0.0
#
#
#############
# START RUN #
#############
#
/run/printProgress 100
/run/beamOn 500
#
#

